name: docker img ci

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [dotnetseleium]
        image-version: [beta]
    steps:
      - uses: actions/checkout@v3
      - name: docker build 
        run: |
          #sudo docker login --username=${docker_hub_user} registry-1.docker.io --password=${{ secrets.docker_hub_pwd }}
          sudo docker build -t ${{ matrix.image-name }}:${{ matrix.image-version }} .
          sudo docker tag ${{ matrix.image-name }}:${{ matrix.image-version }} zhexuezhenhanzi/jin:${{ matrix.image-name }}-${{ matrix.image-version }}
          #sudo docker push zhexuezhenhanzi/jin:${{ matrix.image-name }}-${{ matrix.image-version }}
      - name:  publish
        uses: elgohr/Publish-Docker-Github-Action@2.11
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PWD}}
          registry: ${{secrets.DOCKER_REGISTRY}}
