name: docker img ci

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [dotnetseleium]
        image-version: [beta]
    steps:
      - uses: actions/checkout@v3
      - name: docker build 
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PWD}}
        run: |
          sudo echo "${DOCKER_PASSWORD}"| docker login --username=${docker_hub_user} registry-1.docker.io  --password-stdin
          sudo docker build -t ${{ matrix.image-name }}:${{ matrix.image-version }} .
          sudo docker tag ${{ matrix.image-name }}:${{ matrix.image-version }} zhexuezhenhanzi/jin:${{ matrix.image-name }}-${{ matrix.image-version }}
          sudo docker push zhexuezhenhanzi/jin:${{ matrix.image-name }}-${{ matrix.image-version }}
