name: docker img ci

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [dotnetseleium]
        image-version: [beta]
    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker images
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: zhexuezhenhanzi/jin/dotnetseleium
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}
          registry: index.docker.io
          dockerfile: Dockerfile
          tags: v1
